Experiments first version
Cooperative-IA/CooperativeGPT pull request #25
Opened 2024-02-06 20:27 UTC by JeySeb

- Ajustes en Argumentos pasados por terminal para iniciar la simulación: python main.py args--.
- Corrección de bugs menores con observaciones
- Adición del sistema para experimentación (versión preliminar)
- Ajustes en folder de data/
- Adición de documentación preliminar dentro de data/documentation

2024-02-06 21:48 UTC, Manuel-2011 requested changes
Buenos cambios Juan, el nuevo modulo para hacer la experimentación va a ser de mucha utilidad para mejorar el desempeño de la arquitectura. 
Dejé comentarios de algunas correcciones pequeñas que vi.

2024-02-06 21:48 UTC, Manuel-2011 commented on data/defined_experiments/experiments_definition.md
Que bueno que agregaste un readme y todo! Entonces si se pasa el arg `--agents_bio_config="no_bio"` se inicializarían los agentes con la info de `data/defined_experiments/commons_harvest/agents_context/no_bio`, verdad?

2024-02-06 21:48 UTC, Manuel-2011 commented on data/documentation/repository_doc.md
> +            - b. Is preempted by another agent but eventually takes its turn after all module processes except action execution are completed.
No entendí muy bien este paso

2024-02-06 21:48 UTC, Manuel-2011 commented on data/documentation/repository_doc.md
Está muy buena esta documentación con el funcionamiento como tal del repo

2024-02-06 21:48 UTC, Manuel-2011 commented on game_environment/scene_descriptor/observations_generator.py
> +    def number_to_words(number):
qué hace este método? si se va a empezar a usar sería bueno ponerle el docstring con la descripción

2024-02-06 21:48 UTC, Manuel-2011 commented on game_environment/substrates/python/clean_up.py
> +                  "probabilityTerminationPerInterval": 0
Está bueno. Con este cambio todas las simulaciones deberían durar el número especificado de rondas, no?

2024-02-06 21:48 UTC, Manuel-2011 commented on game_environment/substrates/python/commons_harvest_open.py
> +                  "probabilityTerminationPerInterval": 0.001
Deberíamos ponerle 0 y ya como en el de cleanup, no?

2024-02-06 21:48 UTC, Manuel-2011 commented on game_environment/utils.py
> +        return  ['consume one apple at (x,y)',
Si genera un beneficio el cambio de nombre?

2024-02-06 21:48 UTC, Manuel-2011 commented on main.py
Buenos cambios para simplificar los args que se pasan al script

2024-02-06 21:48 UTC, Manuel-2011 commented on tests/test_observations_generator.py
Me están rompiendo el test nuevo que agregaste, y me rompe otro test de conseguir los elmentos conectados del mapa:
FAILED tests/test_observations_generator.py::test_connected_elems_map - AttributeError: 'ObservationsGenerator' object has no attribute 'connected_elems_map'

FAILED tests/test_observations_generator.py::test_get_new_observed_trees - AssertionError: Expected ['Observed an apple at position [3, 10]. This apple belongs to tree 2.'], got ['Observed an apple at position [1, 23]. This apple belongs to tree 4.', 'Observed an apple ...

2024-02-07 20:09 UTC, JeySeb commented on agent/cognitive_modules/act.py
> +            actions = list(response_dict['actions'])
No hay una mejora muyy sustancial pero si vi que ayudó a evitar comer la ultima manzana en algunos casos, tambien utiliza menos caracteres por lo que se le dice que cree una lista de 3 acciones a partir de 1 solo formato que se le pasa. Previamente teníamos el ejemplo .json mostrandole los 3 formatos

2024-02-07 20:09 UTC, JeySeb commented on data/defined_experiments/experiments_definition.md
Correcto, tambien el folder de defined_experiments tiene un archivo no_bio asociado, así cada substrato manejará los tipos de agentes que se deseen.

2024-02-07 20:09 UTC, JeySeb commented on data/documentation/repository_doc.md
> +            - b. Is preempted by another agent but eventually takes its turn after all module processes except action execution are completed.
Uy creo que eso lo rellenó copilot sin darme cuenta, ya hago la corrección. Gracias por notarlo!

2024-02-07 20:19 UTC, JeySeb commented on data/documentation/repository_doc.md
Gracias! Aún falta la mitad de ese doc y un paso a paso de cómo darle soporte a un nuevo substrato

2024-02-07 20:25 UTC, JeySeb commented on game_environment/scene_descriptor/observations_generator.py
> +    def number_to_words(number):
Era para emplear los números que indican cantidades de forma textual, podría sernos util en caso de que el modelo de lenguaje se vea beneficiado si se le dice "one apple remaining" en vez de "1 apple remaining" pero de momento no es empleado. Le agregaré el docstring y lo dejaré por si en el futuro es de utilidad

2024-02-07 20:25 UTC, JeySeb commented on game_environment/substrates/python/clean_up.py
> +                  "probabilityTerminationPerInterval": 0
Este se debe corregir tal y como se dejó commons_harvest_open

2024-02-07 20:25 UTC, JeySeb commented on game_environment/substrates/python/commons_harvest_open.py
> +                  "probabilityTerminationPerInterval": 0.001
El caso de clean_up esta mal, debo hacerle corrección. El substrato arroja un arror de assertion diciendo que "probabilityTerminationPerInterval" no puede ser 0. Lo que hice fue poner un número de steps que nunca vayamos a superar y una probabilidad muy baja.

2024-02-07 20:47 UTC, JeySeb commented on game_environment/utils.py
> +        return  ['consume one apple at (x,y)',
No podría afirmarlo al 100% pero creo que mitiga un poco la confusión con que "harvest apples" o "grab apples" es cosecharlas y ayuda a que reaparezcan

2024-02-07 20:48 UTC, JeySeb commented on tests/test_observations_generator.py
Vale, los corregiré, el de FAILED tests/test_observations_generator.py::test_connected_elems_map - AttributeError: 'ObservationsGenerator' object has no attribute 'connected_elems_map' también me ocurrió cuando los intenté correr

2024-02-07 21:09 UTC, JeySeb commented
Los cambios necesarios para el PR fueron realiazdos

2024-02-08 19:44 UTC, Manuel-2011 commented on game_environment/scene_descriptor/observations_generator.py
> +    def number_to_words(number):
De acuerdo!

2024-02-08 19:51 UTC, Manuel-2011 commented on agent/cognitive_modules/act.py
> +            actions = list(response_dict['actions'])
Dale, a la final seguimos experimentando para ver que versión final se deja.

2024-02-08 19:51 UTC, Manuel-2011 commented on data/documentation/repository_doc.md
Perfecto!

2024-02-08 19:52 UTC, Manuel-2011 commented on game_environment/scene_descriptor/observations_generator.py
> +    def number_to_words(number):
Listo, no hay problema

2024-02-08 19:53 UTC, Manuel-2011 commented on game_environment/substrates/python/commons_harvest_open.py
> +                  "probabilityTerminationPerInterval": 0.001
Entiendo, dale.

2024-02-08 19:54 UTC, Manuel-2011 commented on game_environment/utils.py
> +        return  ['consume one apple at (x,y)',
Vale, lo seguimos poniendo a prueba con el notebook de experimentación.

2024-02-08 19:55 UTC, Manuel-2011 approved these changes

2024-02-08 20:26 UTC, merged