Origin/new substrates lua
Cooperative-IA/CooperativeGPT pull request #42
Opened 2024-08-25 23:14 UTC by JeySeb

**Substrate Adapter**

- Created the required structure for a whole substrate adapter. It means that adding new substrate should require
    - Created a substrate utils that contains the specific utils for each scenario. It is being imported on every needed class by using the name of the scenario
        - Files as [[main.py](http://main.py/)](http://main.py), [Perceive.py](http://perceive.py/), Observations_generator.py, [[server.py](http://server.py/)](http://server.py) and game_environment/utils.py are not using references to specific scenarios. Only by imports.
    - There are no more known_{specific_object} like known_trees. Now there are only a dictionary of known_objects which contains the name of the known object as a key and as value the components related.
- The complete supported scenarios are the next
    - Commons Harvest Open
    - Clean Up
    - Coins (personalized for 2v2 scenario)
    - External Mushrooms
    - Cooperative Mining
- The next scenarios have only support for .lua file, they are ready to be adjusted to the LLM Agents
    - Collaborative Cooking
    - Factory Of Coomons
    - Hidden Agenda
- Experiment for Humans Interface integrated (for the old version of the functional main)

**Changes for integration**
- All changes were adapted to the Substrate Adapter branch
- Function to check observed changes were divided into a util function and a specific function for Commons Harvest Open
- Added tests in the PR for one step per move still working and were adapted

**For Coins and Externall Mushrooms**
- Recorder and substrate_utils functions were personalized for the substrate with the new way of movement of the game.
- Added detailed and definitions context of the scenario.
- Human_agent have to be checked to correct its functionalities.

2024-08-26 20:55 UTC, Manuel-2011 requested changes
@JeySeb Juan una última cosita que vi es que hay un test que no está pasando, parece ser un nuevo argumento que agregaste a una función, para que porfa lo revises:
FAILED tests/test_scene_descriptor.py::test_describe_scene - TypeError: SceneDescriptor.__init__() missing 1 required positional argument: 'substrate_name'

Dejé algunos comentarios con ajustes pequeños a realizar. En general, me parecieron geniales los cambios para de forma muy limpia manejar diferentes juegos. Me sorprendió el montón de nuevos juegos que pudiste agregar, excelente trabajo.

2024-08-26 20:55 UTC, Manuel-2011 commented on game_environment/playing_utils/level_playing_utils.py
> +            self.game_recorder.record_game_state_before_actions(self.game_ascii_map, curr_global_map, current_actions_map, description, prev_global_map)
@JeySeb Aquí creería que no se necesita pasar el mapa anterior. Lo que pasa es que se tienen dos funciones en el recorder: `record_game_state_before_actions` que revisa el mapa antes de que se tome la acción, y luego `record_elements_status` recibe el mapa luego que se tomó la acción, así que con esas dos se puede revisar si por ejemplo se comío algo o cosas de ese estilo. Te puedes guiar con como se hace en commons harvest.

2024-08-26 20:55 UTC, Manuel-2011 commented on game_environment/scene_descriptor/observations_generator.py
> +    def delete_get_specific_substrate_observations(self, local_map: str, local_position: tuple, global_position: tuple, agent_orientation: int, connected_elments: dict, symbols: dict) -> list[str]:
Esta función se puede eliminar, no? no veo que se use

2024-08-26 20:55 UTC, Manuel-2011 commented on game_environment/scene_descriptor/observations_generator.py
> +    def old_get_observed_changes(self, observed_map: str, last_observed_map: str | None, agent_local_position: tuple, agent_global_position: tuple, agent_last_global_position: tuple, agent_orientatio
Esta función se puede eliminar, no veo que se llame. Pero mira que no veo que los nuevos cambios que había agregado para detectar los cambios en cada paso se estén tomando en cuenta. Creo que faltaría pasar eso al archivo específico de commons harvest

2024-08-26 20:55 UTC, Manuel-2011 commented on game_environment/scene_descriptor/scene_descriptor.py
> +        print(zaps)
Eliminar el print

2024-08-26 20:55 UTC, Manuel-2011 commented on game_environment/substrates/python/commons_harvest_open.py
> +W          Q           W
Este cambio qué objetivo tiene?

2024-08-26 20:55 UTC, Manuel-2011 commented on game_environment/substrates/utilities/commons_harvest_open/substrate_utils.py
> +def get_observed_changes( observed_map: str, last_observed_map: str | None, agent_local_position: tuple, agent_global_position: tuple, agent_last_global_position: tuple, agent_orientation: int, agent
Aquí es donde faltaría copiar los nuevos cambios que había hecho a esta función

2024-08-26 20:55 UTC, Manuel-2011 commented on game_environment/utils.py
> +@staticmethod
El @staticmethod se puede sacar

2024-08-26 20:55 UTC, Manuel-2011 commented on game_environment/utils.py
> +def process_observed_matrices(curr_m: np.ndarray, last_m: np.ndarray, agent_local_position: tuple, agent_global_position: tuple, agent_last_global_position: tuple, agent_orientation: int, agent_last_
aaah no había visto que todo lo encapsulaste aquí para reusar con facilidad. Perfecto!

2024-08-26 20:55 UTC, Manuel-2011 commented on prompts/base_prompts_v1/act.txt
> -Define what should be the nex action for Laura get closer to achieve its goals following the current plan.
Ooops, tremendo error que había jaja

2024-08-26 20:55 UTC, Manuel-2011 commented on tests/test_commons_harvest_recorder.py
> +from game_environment.substrates.utilities.commons_harvest_open.recorder import get_nearest_apple, is_apple_the_last_of_tree, record_game_state_before_actions, record_elements_status
Gracias por no olvidarte de los tests!!!

2024-08-26 20:55 UTC, Manuel-2011 commented on utils/agent_creator.py
De pronto aquí podría agregar el CoT agent

2024-08-26 20:55 UTC, Manuel-2011 commented on utils/args_handler.py
>      parser.add_argument(
Esto creo que no le estamos usando, no?

2024-08-26 20:55 UTC, Manuel-2011 commented on utils/files.py
> +@staticmethod
Se puede sacar el @staticmethod

2024-08-26 21:55 UTC, JeySeb commented on utils/files.py
> +@staticmethod
Hecho

2024-08-26 23:07 UTC, JeySeb commented on game_environment/scene_descriptor/observations_generator.py
> +    def old_get_observed_changes(self, observed_map: str, last_observed_map: str | None, agent_local_position: tuple, agent_global_position: tuple, agent_last_global_position: tuple, agent_orientatio
Vi el otro comentario de que revisaste la función de process_matrix o algo así.
Y eliminaré la función, se me pasó dejarla jeje

2024-08-26 23:09 UTC, JeySeb commented on game_environment/scene_descriptor/observations_generator.py
> +    def delete_get_specific_substrate_observations(self, local_map: str, local_position: tuple, global_position: tuple, agent_orientation: int, connected_elments: dict, symbols: dict) -> list[str]:
Esa también se me pasó, gracias por notarlo!!

2024-08-27 00:33 UTC, JeySeb commented on game_environment/playing_utils/level_playing_utils.py
> +            self.game_recorder.record_game_state_before_actions(self.game_ascii_map, curr_global_map, current_actions_map, description, prev_global_map)
Por los argumentos que recibe record_elements_status no fue posible en coins y en externall_mushrooms calcular algunas metricas que involucran posiciones y otras cosas. Habría que optar por en el futuro cambiar record_elements_status para que reciba esos parametros necesarios. Pero sí tienes razón, debería hacerse luego de tomar la acción

2024-08-27 01:21 UTC, Manuel-2011 approved these changes

2024-08-28 17:06 UTC, merged